################
#
#  Makefile to create a library of functions for the PCR DServ routine
#
#  This file contains only varaibles which are specific to
#    the compilation of the files in this subdirectory.
#
#  General AO compilation parameters are held in
#	../include/Make_Flags
#	../include/Make_Dependenies
#
#-------------------------------------------------------------
#
#  Written  19nov05  DLM  Started with Makefile from MMTAO GUI
#
################
#
# Application dependent variables
#
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# List of functions to include in library
#

LIB = lib_MVP

LIST = 	MVP_Abort.c \
	MVP_Disable.c \
	MVP_Enable.c \
	MVP_HardStop.c \
	MVP_Home.c \
	MVP_HomeFlag.c \
	MVP_Looper.c \
	MVP_MoveAbsolute.c \
	MVP_MoveRelative.c \
	MVP_Position.c \
	MVP_Process.c \
	MVP_PrintDevice.c \
	MVP_PrintStatus.c \
	MVP_Read.c \
	MVP_ResetNode.c \
	MVP_SetAccel.c \
	MVP_SetHomeFlag.c \
	MVP_SetHomeTrigger.c \
	MVP_SetSpeed.c \
	MVP_SetZero.c \
	MVP_Status.c \
	MVP_Write.c

#
# ** Edit only variables above this line **
#
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Compiler specifics
#
include ../include/Topbox_Make_Flags
#
# Compile and archive functions
#
include ../include/Topbox_Make_Dependencies
