
static ErrorList ErrorTable[] = {
{ 0, "OK" },				
{ PCR_LOOP_PANIC, "Loop Panic" },
{ PCR_RTR_DELTAS_TOO_LARGE, "Calculated RTR Deltas are too large" },
{ PCR_OPEN_BUT_SAFE_EXIT, "Loop Open on Request" },
{ PCR_DM_COMM_ERROR, "Mirror communication error"},
{ PCR_COMM_ERROR, "Generic communication error"},			
{ PCR_GENERIC_ERROR, "Generic system error"},			
{ PCR_INPUT_ERROR , "Parameter input error" },
{ PCR_TYPE_ERROR, "Client command type error" },
{ PCR_FILEIO_ERROR, "Generic file I/O error" },
{ PCR_NETWORK_ERROR, "Generic network error" },			
{ PCR_THREAD_ERROR, "Thread creation error" },			
{ PCR_DISKFULL_ERROR, "No space on disk" },
{ PCR_FIFO_ERROR, "Unable to create named pipe" },		
{ PCR_MEMORY_ALLOC_ERROR,"Memory allocation error"},	
{ PCR_NGS_CAMERA_ERROR, "Generic camera error" },
{ PCR_NGS_CONFIG_ERR0R, "Camera configuration error" },
{ PCR_NGS_FRAME_RATE_ERROR, "Wrong frame rate"},
{ PCR_NGS_COMM_ERROR, "Camera communication error" },
{ PCR_NGS_CAMSIZE_ERROR, "Unable to set frame size"},
{ PCR_NGS_CAM_SERIALPORT_ERROR, "Camera serial port error"},  	
{ PCR_VARIABLES_INIT_ERROR, "Initialization error" },
{ PCR_SSC_ERROR, "Generic slope calculation error" },
{ PCR_SSC_SLUTREAD_NOTOK,"Slope lookup table read error" },
{ PCR_MODAL_MATRIX_READ_NOTOK, "Modal matrix read error"},
{ PCR_SYSTEM_GAIN_READ_NOTOK, "System gain read error" },
{ PCR_ACT_READ_NOTOK, "Invalid actuator list read error" },
{ PCR_SSC_MALLOC_FAILED, "SSC memory allocation error"},
{ PCR_MODAL_INIT_ERROR,"Modal matrix initialization error" },
{ PCR_RTR_ERROR, "Wavefont reconstruction error"},
{ PCR_RTR_MATRIX_READ_NOTOK, "RTR matrix read error" },
{ PCR_DMI_ERROR, "Generic mirror interface error" },
{ PCR_DMI_FLAT_POS_ERROR, "Error reading flat" },
{ PCR_DMI_MODAL_TERM_CALC_ERROR, "Error in modal error calculation" },
{ PCR_BCU_ERROR	, "Generic BCU error"},
{ PCR_BCU_SOCKET_LOCK_ERROR, "Socket Lock error" },
{ PCR_BCU_ETH_ERROR, "No ethernet signal" },
{ PCR_BCU_JUMBOFRAME_ERROR, "MTU config error"},
{ PCR_BCU_TIMEOUT_ERROR, "Timeout error from mirror" }, 
{ PCR_DDS_ERROR, "Generic DDS error" },
{ PCR_DDS_FIFO_OPEN_NOTOK, "DDS broken pipe" },
{ PCR_DDS_BUFFER_ERROR, "error in DDS buffer" },
{ PCR_DBASE_ERROR, "Generic database error" },
};
